/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu;

/**
 *
 * @author putur
 */
public class Dashboards extends javax.swing.JFrame {

    /**
     * Creates new form Dashboards
     */
    public Dashboards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Tugas = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        Statistik = new javax.swing.JLabel();
        PanelAtas = new javax.swing.JPanel();
        HaloUser = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Profil = new javax.swing.JLabel();
        TugasHariIni = new javax.swing.JPanel();
        HeadTugasHariIni = new javax.swing.JLabel();
        PanelTgsHriIni = new java.awt.Panel();
        JudulTugas = new javax.swing.JLabel();
        ProgresTugas = new javax.swing.JProgressBar();
        WaktuTanggalDeadline = new javax.swing.JLabel();
        PresentaseProgres = new javax.swing.JLabel();
        LihatSemuaTugas = new javax.swing.JLabel();
        TanggalHariIni = new javax.swing.JLabel();
        StatistikPanelUtama = new javax.swing.JPanel();
        HeadJudulStatistik = new javax.swing.JLabel();
        ReminderPanel = new javax.swing.JPanel();
        PanelTugas1Remind = new java.awt.Panel();
        TanggalWaktuDeadlineTugasRemind1 = new javax.swing.JLabel();
        JudulTugasRemind1 = new javax.swing.JLabel();
        PanelTugasRemind2 = new java.awt.Panel();
        JudulTugasRemind2 = new javax.swing.JLabel();
        TanggalWaktuDeadlineRemind2 = new javax.swing.JLabel();
        PanelDetailReminder = new java.awt.Panel();
        DetailReminder = new javax.swing.JLabel();
        HeadReminder = new javax.swing.JLabel();
        TanggalStart = new javax.swing.JLabel();
        TanggalEnd = new javax.swing.JLabel();
        PenghubungTanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(248, 244, 225));
        MainPanel.setPreferredSize(new java.awt.Dimension(375, 812));

        Navbar.setBackground(new java.awt.Color(255, 174, 57));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Beranda.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        Tugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tugas.png"))); // NOI18N
        Tugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TugasMouseClicked(evt);
            }
        });

        Timer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Timmer.png"))); // NOI18N
        Timer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimerMouseClicked(evt);
            }
        });

        Statistik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Statistik.png"))); // NOI18N
        Statistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatistikMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Home)
                .addGap(40, 40, 40)
                .addComponent(Tugas)
                .addGap(40, 40, 40)
                .addComponent(Timer)
                .addGap(40, 40, 40)
                .addComponent(Statistik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Statistik))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelAtas.setBackground(new java.awt.Color(255, 174, 57));
        PanelAtas.setForeground(new java.awt.Color(102, 0, 102));

        HaloUser.setBackground(new java.awt.Color(0, 0, 153));
        HaloUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HaloUser.setForeground(new java.awt.Color(0, 0, 153));
        HaloUser.setText("Halo, Username");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/_(95 x 95 piksel).png"))); // NOI18N

        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Profil.png"))); // NOI18N
        Profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelAtasLayout = new javax.swing.GroupLayout(PanelAtas);
        PanelAtas.setLayout(PanelAtasLayout);
        PanelAtasLayout.setHorizontalGroup(
            PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAtasLayout.createSequentialGroup()
                        .addComponent(HaloUser)
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(PanelAtasLayout.createSequentialGroup()
                        .addComponent(Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Profil)
                        .addGap(27, 27, 27))))
        );
        PanelAtasLayout.setVerticalGroup(
            PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtasLayout.createSequentialGroup()
                .addGroup(PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAtasLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAtasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Profil)
                        .addGap(18, 18, 18)))
                .addComponent(HaloUser)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        TugasHariIni.setBackground(new java.awt.Color(250, 227, 143));

        HeadTugasHariIni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HeadTugasHariIni.setForeground(new java.awt.Color(0, 0, 153));
        HeadTugasHariIni.setText("Tugas Hari Ini");

        PanelTgsHriIni.setBackground(new java.awt.Color(255, 252, 235));

        JudulTugas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JudulTugas.setForeground(new java.awt.Color(0, 0, 102));
        JudulTugas.setText("Judul Tugas");

        WaktuTanggalDeadline.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        WaktuTanggalDeadline.setForeground(new java.awt.Color(0, 0, 102));
        WaktuTanggalDeadline.setText("Deadline");

        PresentaseProgres.setForeground(new java.awt.Color(0, 0, 102));
        PresentaseProgres.setText("0%");

        javax.swing.GroupLayout PanelTgsHriIniLayout = new javax.swing.GroupLayout(PanelTgsHriIni);
        PanelTgsHriIni.setLayout(PanelTgsHriIniLayout);
        PanelTgsHriIniLayout.setHorizontalGroup(
            PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                        .addComponent(JudulTugas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                        .addGroup(PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                                .addComponent(WaktuTanggalDeadline)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ProgresTugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PresentaseProgres)
                        .addGap(14, 14, 14))))
        );
        PanelTgsHriIniLayout.setVerticalGroup(
            PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIniLayout.createSequentialGroup()
                        .addComponent(JudulTugas)
                        .addGap(1, 1, 1)
                        .addComponent(WaktuTanggalDeadline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProgresTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIniLayout.createSequentialGroup()
                        .addComponent(PresentaseProgres)
                        .addContainerGap())))
        );

        LihatSemuaTugas.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        LihatSemuaTugas.setForeground(new java.awt.Color(0, 0, 153));
        LihatSemuaTugas.setText("Lihat Semua Tugas Hari Ini");
        LihatSemuaTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LihatSemuaTugasMouseClicked(evt);
            }
        });

        TanggalHariIni.setForeground(new java.awt.Color(0, 0, 153));
        TanggalHariIni.setText("DD-MM-YY");

        javax.swing.GroupLayout TugasHariIniLayout = new javax.swing.GroupLayout(TugasHariIni);
        TugasHariIni.setLayout(TugasHariIniLayout);
        TugasHariIniLayout.setHorizontalGroup(
            TugasHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TugasHariIniLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(TanggalHariIni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TugasHariIniLayout.createSequentialGroup()
                .addGroup(TugasHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TugasHariIniLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LihatSemuaTugas))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TugasHariIniLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelTgsHriIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TugasHariIniLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(HeadTugasHariIni)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TugasHariIniLayout.setVerticalGroup(
            TugasHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TugasHariIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadTugasHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanggalHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTgsHriIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LihatSemuaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StatistikPanelUtama.setBackground(new java.awt.Color(250, 227, 143));

        HeadJudulStatistik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HeadJudulStatistik.setForeground(new java.awt.Color(0, 0, 153));
        HeadJudulStatistik.setText("Statistik Belajar");

        javax.swing.GroupLayout StatistikPanelUtamaLayout = new javax.swing.GroupLayout(StatistikPanelUtama);
        StatistikPanelUtama.setLayout(StatistikPanelUtamaLayout);
        StatistikPanelUtamaLayout.setHorizontalGroup(
            StatistikPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatistikPanelUtamaLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(HeadJudulStatistik)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        StatistikPanelUtamaLayout.setVerticalGroup(
            StatistikPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatistikPanelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadJudulStatistik)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        ReminderPanel.setBackground(new java.awt.Color(250, 227, 143));

        PanelTugas1Remind.setBackground(new java.awt.Color(255, 252, 235));

        TanggalWaktuDeadlineTugasRemind1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        TanggalWaktuDeadlineTugasRemind1.setForeground(new java.awt.Color(0, 0, 102));
        TanggalWaktuDeadlineTugasRemind1.setText("Deadlie Pegumpulan");

        JudulTugasRemind1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        JudulTugasRemind1.setForeground(new java.awt.Color(0, 0, 102));
        JudulTugasRemind1.setText("Judul Tugas");

        javax.swing.GroupLayout PanelTugas1RemindLayout = new javax.swing.GroupLayout(PanelTugas1Remind);
        PanelTugas1Remind.setLayout(PanelTugas1RemindLayout);
        PanelTugas1RemindLayout.setHorizontalGroup(
            PanelTugas1RemindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTugas1RemindLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTugas1RemindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulTugasRemind1)
                    .addComponent(TanggalWaktuDeadlineTugasRemind1))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PanelTugas1RemindLayout.setVerticalGroup(
            PanelTugas1RemindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTugas1RemindLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugasRemind1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanggalWaktuDeadlineTugasRemind1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTugasRemind2.setBackground(new java.awt.Color(255, 252, 235));

        JudulTugasRemind2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        JudulTugasRemind2.setForeground(new java.awt.Color(0, 0, 102));
        JudulTugasRemind2.setText("Judul Tugas");

        TanggalWaktuDeadlineRemind2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        TanggalWaktuDeadlineRemind2.setForeground(new java.awt.Color(0, 0, 102));
        TanggalWaktuDeadlineRemind2.setText("Deadlie Pegumpulan");

        javax.swing.GroupLayout PanelTugasRemind2Layout = new javax.swing.GroupLayout(PanelTugasRemind2);
        PanelTugasRemind2.setLayout(PanelTugasRemind2Layout);
        PanelTugasRemind2Layout.setHorizontalGroup(
            PanelTugasRemind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTugasRemind2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTugasRemind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulTugasRemind2)
                    .addComponent(TanggalWaktuDeadlineRemind2))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PanelTugasRemind2Layout.setVerticalGroup(
            PanelTugasRemind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTugasRemind2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugasRemind2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanggalWaktuDeadlineRemind2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        DetailReminder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Show More.png"))); // NOI18N
        DetailReminder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetailReminderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelDetailReminderLayout = new javax.swing.GroupLayout(PanelDetailReminder);
        PanelDetailReminder.setLayout(PanelDetailReminderLayout);
        PanelDetailReminderLayout.setHorizontalGroup(
            PanelDetailReminderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetailReminderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DetailReminder)
                .addContainerGap())
        );
        PanelDetailReminderLayout.setVerticalGroup(
            PanelDetailReminderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetailReminderLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(DetailReminder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HeadReminder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HeadReminder.setForeground(new java.awt.Color(0, 0, 153));
        HeadReminder.setText("Reminder Deadline");

        TanggalStart.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TanggalStart.setForeground(new java.awt.Color(0, 0, 153));
        TanggalStart.setText("DD-MM-YY");

        TanggalEnd.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TanggalEnd.setForeground(new java.awt.Color(0, 0, 153));
        TanggalEnd.setText("DD-MM-YY");

        PenghubungTanggal.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        PenghubungTanggal.setForeground(new java.awt.Color(0, 0, 153));
        PenghubungTanggal.setText("-");

        javax.swing.GroupLayout ReminderPanelLayout = new javax.swing.GroupLayout(ReminderPanel);
        ReminderPanel.setLayout(ReminderPanelLayout);
        ReminderPanelLayout.setHorizontalGroup(
            ReminderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReminderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTugas1Remind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTugasRemind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDetailReminder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReminderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReminderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HeadReminder)
                    .addGroup(ReminderPanelLayout.createSequentialGroup()
                        .addComponent(TanggalStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PenghubungTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TanggalEnd)))
                .addGap(104, 104, 104))
        );
        ReminderPanelLayout.setVerticalGroup(
            ReminderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReminderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadReminder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReminderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanggalEnd)
                    .addComponent(TanggalStart)
                    .addComponent(PenghubungTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReminderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelTugasRemind2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTugas1Remind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDetailReminder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(PanelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TugasHariIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReminderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatistikPanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(PanelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TugasHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReminderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatistikPanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        new Dashboards().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void TugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TugasMouseClicked
        new Tugas().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TugasMouseClicked

    private void TimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimerMouseClicked
        new Timer().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TimerMouseClicked

    private void StatistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatistikMouseClicked
        new Statistik().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_StatistikMouseClicked

    private void DetailReminderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailReminderMouseClicked
        new Reminder().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_DetailReminderMouseClicked

    private void ProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilMouseClicked
        new Profil().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ProfilMouseClicked

    private void LihatSemuaTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LihatSemuaTugasMouseClicked
        new TugasHariIni().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_LihatSemuaTugasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetailReminder;
    private javax.swing.JLabel HaloUser;
    private javax.swing.JLabel HeadJudulStatistik;
    private javax.swing.JLabel HeadReminder;
    private javax.swing.JLabel HeadTugasHariIni;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel JudulTugas;
    private javax.swing.JLabel JudulTugasRemind1;
    private javax.swing.JLabel JudulTugasRemind2;
    private javax.swing.JLabel LihatSemuaTugas;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel PanelAtas;
    private java.awt.Panel PanelDetailReminder;
    private java.awt.Panel PanelTgsHriIni;
    private java.awt.Panel PanelTugas1Remind;
    private java.awt.Panel PanelTugasRemind2;
    private javax.swing.JLabel PenghubungTanggal;
    private javax.swing.JLabel PresentaseProgres;
    private javax.swing.JLabel Profil;
    private javax.swing.JProgressBar ProgresTugas;
    private javax.swing.JPanel ReminderPanel;
    private javax.swing.JLabel Statistik;
    private javax.swing.JPanel StatistikPanelUtama;
    private javax.swing.JLabel TanggalEnd;
    private javax.swing.JLabel TanggalHariIni;
    private javax.swing.JLabel TanggalStart;
    private javax.swing.JLabel TanggalWaktuDeadlineRemind2;
    private javax.swing.JLabel TanggalWaktuDeadlineTugasRemind1;
    private javax.swing.JLabel Timer;
    private javax.swing.JLabel Tugas;
    private javax.swing.JPanel TugasHariIni;
    private javax.swing.JLabel WaktuTanggalDeadline;
    // End of variables declaration//GEN-END:variables
}
