/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu;

/**
 *
 * @author putur
 */
public class Profil extends javax.swing.JFrame {

    /**
     * Creates new form Profil
     */
    public Profil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelTgsHriIni = new java.awt.Panel();
        JudulTugas6 = new javax.swing.JLabel();
        JudulTugas1 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        PanelTgsHriIni1 = new java.awt.Panel();
        JudulTugas2 = new javax.swing.JLabel();
        PanelTgsHriIni2 = new java.awt.Panel();
        PanelTgsHriIni3 = new java.awt.Panel();
        JudulTugas4 = new javax.swing.JLabel();
        PanelTgsHriIni4 = new java.awt.Panel();
        JudulTugas5 = new javax.swing.JLabel();
        JudulTugas = new javax.swing.JLabel();
        JudulTugas3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(248, 244, 225));
        MainPanel.setPreferredSize(new java.awt.Dimension(375, 812));

        PanelTgsHriIni.setBackground(new java.awt.Color(144, 209, 202));

        JudulTugas6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulTugas6.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas6.setText("UsernameUser");
        JudulTugas6.setToolTipText("");

        javax.swing.GroupLayout PanelTgsHriIniLayout = new javax.swing.GroupLayout(PanelTgsHriIni);
        PanelTgsHriIni.setLayout(PanelTgsHriIniLayout);
        PanelTgsHriIniLayout.setHorizontalGroup(
            PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugas6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        PanelTgsHriIniLayout.setVerticalGroup(
            PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JudulTugas6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JudulTugas1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JudulTugas1.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas1.setText("Profile");

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NewBack.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        PanelTgsHriIni1.setBackground(new java.awt.Color(144, 209, 202));

        JudulTugas2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulTugas2.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas2.setText("Keluar");

        javax.swing.GroupLayout PanelTgsHriIni1Layout = new javax.swing.GroupLayout(PanelTgsHriIni1);
        PanelTgsHriIni1.setLayout(PanelTgsHriIni1Layout);
        PanelTgsHriIni1Layout.setHorizontalGroup(
            PanelTgsHriIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(JudulTugas2)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        PanelTgsHriIni1Layout.setVerticalGroup(
            PanelTgsHriIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JudulTugas2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PanelTgsHriIni2.setBackground(new java.awt.Color(144, 209, 202));

        javax.swing.GroupLayout PanelTgsHriIni2Layout = new javax.swing.GroupLayout(PanelTgsHriIni2);
        PanelTgsHriIni2.setLayout(PanelTgsHriIni2Layout);
        PanelTgsHriIni2Layout.setHorizontalGroup(
            PanelTgsHriIni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        PanelTgsHriIni2Layout.setVerticalGroup(
            PanelTgsHriIni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        PanelTgsHriIni3.setBackground(new java.awt.Color(144, 209, 202));

        JudulTugas4.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas4.setText("Email");

        javax.swing.GroupLayout PanelTgsHriIni3Layout = new javax.swing.GroupLayout(PanelTgsHriIni3);
        PanelTgsHriIni3.setLayout(PanelTgsHriIni3Layout);
        PanelTgsHriIni3Layout.setHorizontalGroup(
            PanelTgsHriIni3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugas4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTgsHriIni3Layout.setVerticalGroup(
            PanelTgsHriIni3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni3Layout.createSequentialGroup()
                .addComponent(JudulTugas4)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        PanelTgsHriIni4.setBackground(new java.awt.Color(144, 209, 202));

        JudulTugas5.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas5.setText("Universitas");

        javax.swing.GroupLayout PanelTgsHriIni4Layout = new javax.swing.GroupLayout(PanelTgsHriIni4);
        PanelTgsHriIni4.setLayout(PanelTgsHriIni4Layout);
        PanelTgsHriIni4Layout.setHorizontalGroup(
            PanelTgsHriIni4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugas5)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        PanelTgsHriIni4Layout.setVerticalGroup(
            PanelTgsHriIni4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni4Layout.createSequentialGroup()
                .addComponent(JudulTugas5)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        JudulTugas.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas.setText("Username");

        JudulTugas3.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas3.setText("Nama Lengkap");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PanelTgsHriIni3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelTgsHriIni4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Back)
                            .addGap(102, 102, 102)
                            .addComponent(JudulTugas1)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTgsHriIni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelTgsHriIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JudulTugas)
                            .addComponent(JudulTugas3))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelTgsHriIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back)
                    .addComponent(JudulTugas1))
                .addGap(29, 29, 29)
                .addComponent(JudulTugas)
                .addGap(2, 2, 2)
                .addComponent(PanelTgsHriIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(JudulTugas3)
                .addGap(51, 51, 51)
                .addComponent(PanelTgsHriIni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PanelTgsHriIni4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PanelTgsHriIni3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(PanelTgsHriIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new Dashboards().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel JudulTugas;
    private javax.swing.JLabel JudulTugas1;
    private javax.swing.JLabel JudulTugas2;
    private javax.swing.JLabel JudulTugas3;
    private javax.swing.JLabel JudulTugas4;
    private javax.swing.JLabel JudulTugas5;
    private javax.swing.JLabel JudulTugas6;
    private javax.swing.JPanel MainPanel;
    private java.awt.Panel PanelTgsHriIni;
    private java.awt.Panel PanelTgsHriIni1;
    private java.awt.Panel PanelTgsHriIni2;
    private java.awt.Panel PanelTgsHriIni3;
    private java.awt.Panel PanelTgsHriIni4;
    // End of variables declaration//GEN-END:variables
}
