/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
/**
 *
 * @author putur
 */
public class TambahTugas extends javax.swing.JFrame {

    /**
     * Creates new form x
     */
    public TambahTugas() {
        initComponents();
        sVGIcon1.setSVGIcon("icon/NewBack.svg", 40, 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        MainPanel = new javax.swing.JPanel();
        Navbar2 = new javax.swing.JPanel();
        Home2 = new javax.swing.JLabel();
        Tugas2 = new javax.swing.JLabel();
        Timer2 = new javax.swing.JLabel();
        Statistik2 = new javax.swing.JLabel();
        JudulTugasTambah = new javax.swing.JTextField();
        DeskripsiTugas = new javax.swing.JScrollPane();
        DescTugasTambah = new javax.swing.JTextArea();
        WaktuTugasTambah = new javax.swing.JTextField();
        DeadlineTugasTambah = new com.toedter.calendar.JDateChooser();
        WaktuTanggalDeadline = new javax.swing.JLabel();
        WaktuTanggalDeadline1 = new javax.swing.JLabel();
        WaktuTanggalDeadline2 = new javax.swing.JLabel();
        WaktuTanggalDeadline3 = new javax.swing.JLabel();
        TambahTugas = new javax.swing.JButton();
        PanelAtas = new javax.swing.JPanel();
        JudulTugas1 = new javax.swing.JLabel();
        sVGIcon1 = new edu.SVGIcon();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(248, 244, 225));
        MainPanel.setPreferredSize(new java.awt.Dimension(375, 812));

        Navbar2.setBackground(new java.awt.Color(255, 174, 57));
        Navbar2.setForeground(new java.awt.Color(247, 247, 247));

        Home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Beranda.png"))); // NOI18N
        Home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home2MouseClicked(evt);
            }
        });

        Tugas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tugas.png"))); // NOI18N
        Tugas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tugas2MouseClicked(evt);
            }
        });

        Timer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Timmer.png"))); // NOI18N
        Timer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Timer2MouseClicked(evt);
            }
        });

        Statistik2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Statistik.png"))); // NOI18N
        Statistik2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Statistik2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Navbar2Layout = new javax.swing.GroupLayout(Navbar2);
        Navbar2.setLayout(Navbar2Layout);
        Navbar2Layout.setHorizontalGroup(
            Navbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navbar2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Home2)
                .addGap(40, 40, 40)
                .addComponent(Tugas2)
                .addGap(40, 40, 40)
                .addComponent(Timer2)
                .addGap(40, 40, 40)
                .addComponent(Statistik2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        Navbar2Layout.setVerticalGroup(
            Navbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navbar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Navbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tugas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Timer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Statistik2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        JudulTugasTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudulTugasTambahActionPerformed(evt);
            }
        });

        DescTugasTambah.setColumns(20);
        DescTugasTambah.setRows(5);
        DeskripsiTugas.setViewportView(DescTugasTambah);

        WaktuTugasTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaktuTugasTambahActionPerformed(evt);
            }
        });

        WaktuTanggalDeadline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline.setForeground(new java.awt.Color(0, 0, 153));
        WaktuTanggalDeadline.setText("Waktu Deadline");

        WaktuTanggalDeadline1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline1.setForeground(new java.awt.Color(0, 0, 153));
        WaktuTanggalDeadline1.setText("Judul Tugas");

        WaktuTanggalDeadline2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline2.setForeground(new java.awt.Color(0, 0, 153));
        WaktuTanggalDeadline2.setText("Tanggal Deadline");

        WaktuTanggalDeadline3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline3.setForeground(new java.awt.Color(0, 0, 153));
        WaktuTanggalDeadline3.setText("Deskripsi Tugas");

        TambahTugas.setBackground(new java.awt.Color(250, 227, 143));
        TambahTugas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahTugas.setForeground(new java.awt.Color(0, 0, 153));
        TambahTugas.setText("Tambah Tugas");
        TambahTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahTugasActionPerformed(evt);
            }
        });

        PanelAtas.setBackground(new java.awt.Color(255, 174, 57));
        PanelAtas.setForeground(new java.awt.Color(102, 0, 102));

        JudulTugas1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JudulTugas1.setForeground(new java.awt.Color(0, 0, 153));
        JudulTugas1.setText("Tugas");

        sVGIcon1.setText("sVGIcon1");

        javax.swing.GroupLayout PanelAtasLayout = new javax.swing.GroupLayout(PanelAtas);
        PanelAtas.setLayout(PanelAtasLayout);
        PanelAtasLayout.setHorizontalGroup(
            PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(sVGIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(JudulTugas1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAtasLayout.setVerticalGroup(
            PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JudulTugas1)
                    .addComponent(sVGIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WaktuTugasTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JudulTugasTambah)
                                .addComponent(DeskripsiTugas)
                                .addComponent(DeadlineTugasTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(WaktuTanggalDeadline, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuTanggalDeadline1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuTanggalDeadline2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuTanggalDeadline3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(TambahTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(PanelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WaktuTanggalDeadline1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JudulTugasTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WaktuTanggalDeadline2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeadlineTugasTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WaktuTanggalDeadline)
                .addGap(4, 4, 4)
                .addComponent(WaktuTugasTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WaktuTanggalDeadline3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeskripsiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TambahTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Navbar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home2MouseClicked
        new Dashboards().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Home2MouseClicked

    private void Tugas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tugas2MouseClicked
        new Tugas().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Tugas2MouseClicked

    private void Timer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Timer2MouseClicked
        new Timer().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Timer2MouseClicked

    private void Statistik2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Statistik2MouseClicked
        new Statistik().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Statistik2MouseClicked

    private void JudulTugasTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudulTugasTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JudulTugasTambahActionPerformed

    private void WaktuTugasTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaktuTugasTambahActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_WaktuTugasTambahActionPerformed

    private void TambahTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahTugasActionPerformed

    String judul = JudulTugasTambah.getText().trim(); // nama_tugas
    String deskripsi = DescTugasTambah.getText().trim();   // deskripsi
    java.util.Date selectedDate = DeadlineTugasTambah.getDate(); // tanggal_deadline
    String jam = WaktuTugasTambah.getText().trim(); // Format: "HH:mm:ss"

    if (judul.isEmpty() || deskripsi.isEmpty() || selectedDate == null || jam.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi dengan lengkap.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validasi format waktu jam, minimal: HH:mm (bisa dikembangkan)
    if (!jam.matches("^([01]?\\d|2[0-3]):[0-5]\\d(:[0-5]\\d)?$")) {
        JOptionPane.showMessageDialog(this, "Format waktu deadline harus HH:mm atau HH:mm:ss", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Gabungkan tanggal dan waktu menjadi satu string datetime untuk database
    java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String tanggalStr = dateFormat.format(selectedDate);
    String datetimeStr = tanggalStr + " " + jam;

    try {
        String sql = "INSERT INTO tugas (nama_tugas, tanggal_deadline, jam_deadline, deskripsi) VALUES (?, ?, ?, ?)";

        PreparedStatement pst = Koneksi.configDB().prepareStatement(sql);
        pst.setString(1, judul);
        pst.setString(2, tanggalStr);
        pst.setString(3, jam);
        pst.setString(4, deskripsi);

        int rowsInserted = pst.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Tugas berhasil disimpan.");
            // Reset form
            JudulTugasTambah.setText("");
            DescTugasTambah.setText("");
            DeadlineTugasTambah.setDate(null);
            WaktuTugasTambah.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan tugas.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahTugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahTugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DeadlineTugasTambah;
    private javax.swing.JTextArea DescTugasTambah;
    private javax.swing.JScrollPane DeskripsiTugas;
    private javax.swing.JLabel Home2;
    private javax.swing.JLabel JudulTugas1;
    private javax.swing.JTextField JudulTugasTambah;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Navbar2;
    private javax.swing.JPanel PanelAtas;
    private javax.swing.JLabel Statistik2;
    private javax.swing.JButton TambahTugas;
    private javax.swing.JLabel Timer2;
    private javax.swing.JLabel Tugas2;
    private javax.swing.JLabel WaktuTanggalDeadline;
    private javax.swing.JLabel WaktuTanggalDeadline1;
    private javax.swing.JLabel WaktuTanggalDeadline2;
    private javax.swing.JLabel WaktuTanggalDeadline3;
    private javax.swing.JTextField WaktuTugasTambah;
    private javax.swing.JInternalFrame jInternalFrame1;
    private edu.SVGIcon sVGIcon1;
    // End of variables declaration//GEN-END:variables
}
