/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu;

/**
 *
 * @author putur
 */
public class Tugas extends javax.swing.JFrame {

    /**
     * Creates new form Tugas
     */
    public Tugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelTgsHriIni = new java.awt.Panel();
        JudulTugas = new javax.swing.JLabel();
        ProgresTugas = new javax.swing.JProgressBar();
        WaktuTanggalDeadline = new javax.swing.JLabel();
        PresentaseProgres = new javax.swing.JLabel();
        WaktuTanggalDeadline1 = new javax.swing.JLabel();
        JudulTugas1 = new javax.swing.JLabel();
        PanelTgsHriIni1 = new java.awt.Panel();
        JudulTugas2 = new javax.swing.JLabel();
        ProgresTugas1 = new javax.swing.JProgressBar();
        WaktuTanggalDeadline2 = new javax.swing.JLabel();
        PresentaseProgres1 = new javax.swing.JLabel();
        WaktuTanggalDeadline3 = new javax.swing.JLabel();
        PanelTgsHriIni2 = new java.awt.Panel();
        JudulTugas3 = new javax.swing.JLabel();
        ProgresTugas2 = new javax.swing.JProgressBar();
        WaktuTanggalDeadline4 = new javax.swing.JLabel();
        PresentaseProgres2 = new javax.swing.JLabel();
        WaktuTanggalDeadline5 = new javax.swing.JLabel();
        PanelTgsHriIni3 = new java.awt.Panel();
        JudulTugas4 = new javax.swing.JLabel();
        ProgresTugas3 = new javax.swing.JProgressBar();
        WaktuTanggalDeadline6 = new javax.swing.JLabel();
        PresentaseProgres3 = new javax.swing.JLabel();
        WaktuTanggalDeadline7 = new javax.swing.JLabel();
        Navbar2 = new javax.swing.JPanel();
        Home2 = new javax.swing.JLabel();
        Tugas2 = new javax.swing.JLabel();
        Timer2 = new javax.swing.JLabel();
        Statistik2 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        AddTugas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(248, 244, 225));
        MainPanel.setPreferredSize(new java.awt.Dimension(375, 812));

        PanelTgsHriIni.setBackground(new java.awt.Color(255, 255, 255));

        JudulTugas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulTugas.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas.setText("Judul Tugas");

        ProgresTugas.setBackground(new java.awt.Color(255, 222, 183));

        WaktuTanggalDeadline.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline.setText("Deadline");

        PresentaseProgres.setForeground(new java.awt.Color(33, 52, 72));
        PresentaseProgres.setText("0%");

        WaktuTanggalDeadline1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        WaktuTanggalDeadline1.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline1.setText("Deskripsi");

        javax.swing.GroupLayout PanelTgsHriIniLayout = new javax.swing.GroupLayout(PanelTgsHriIni);
        PanelTgsHriIni.setLayout(PanelTgsHriIniLayout);
        PanelTgsHriIniLayout.setHorizontalGroup(
            PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                        .addComponent(ProgresTugas, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PresentaseProgres)
                        .addGap(14, 14, 14))
                    .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                        .addGroup(PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuTanggalDeadline)
                            .addComponent(WaktuTanggalDeadline1))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(JudulTugas)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelTgsHriIniLayout.setVerticalGroup(
            PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugas)
                .addGap(2, 2, 2)
                .addComponent(WaktuTanggalDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaktuTanggalDeadline1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(PanelTgsHriIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIniLayout.createSequentialGroup()
                        .addComponent(ProgresTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIniLayout.createSequentialGroup()
                        .addComponent(PresentaseProgres)
                        .addContainerGap())))
        );

        JudulTugas1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JudulTugas1.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas1.setText("Tugas");

        PanelTgsHriIni1.setBackground(new java.awt.Color(255, 255, 255));

        JudulTugas2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulTugas2.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas2.setText("Judul Tugas");

        ProgresTugas1.setBackground(new java.awt.Color(255, 222, 183));

        WaktuTanggalDeadline2.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline2.setText("Deadline");

        PresentaseProgres1.setForeground(new java.awt.Color(33, 52, 72));
        PresentaseProgres1.setText("0%");

        WaktuTanggalDeadline3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        WaktuTanggalDeadline3.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline3.setText("Deskripsi");

        javax.swing.GroupLayout PanelTgsHriIni1Layout = new javax.swing.GroupLayout(PanelTgsHriIni1);
        PanelTgsHriIni1.setLayout(PanelTgsHriIni1Layout);
        PanelTgsHriIni1Layout.setHorizontalGroup(
            PanelTgsHriIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelTgsHriIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTgsHriIni1Layout.createSequentialGroup()
                        .addComponent(ProgresTugas1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PresentaseProgres1)
                        .addGap(14, 14, 14))
                    .addGroup(PanelTgsHriIni1Layout.createSequentialGroup()
                        .addGroup(PanelTgsHriIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuTanggalDeadline2)
                            .addComponent(WaktuTanggalDeadline3))
                        .addGap(0, 295, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JudulTugas2)
                .addGap(133, 133, 133))
        );
        PanelTgsHriIni1Layout.setVerticalGroup(
            PanelTgsHriIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugas2)
                .addGap(2, 2, 2)
                .addComponent(WaktuTanggalDeadline2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaktuTanggalDeadline3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(PanelTgsHriIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni1Layout.createSequentialGroup()
                        .addComponent(ProgresTugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni1Layout.createSequentialGroup()
                        .addComponent(PresentaseProgres1)
                        .addContainerGap())))
        );

        PanelTgsHriIni2.setBackground(new java.awt.Color(255, 255, 255));

        JudulTugas3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulTugas3.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas3.setText("Judul Tugas");

        ProgresTugas2.setBackground(new java.awt.Color(255, 222, 183));

        WaktuTanggalDeadline4.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline4.setText("Deadline");

        PresentaseProgres2.setForeground(new java.awt.Color(33, 52, 72));
        PresentaseProgres2.setText("0%");

        WaktuTanggalDeadline5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        WaktuTanggalDeadline5.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline5.setText("Deskripsi");

        javax.swing.GroupLayout PanelTgsHriIni2Layout = new javax.swing.GroupLayout(PanelTgsHriIni2);
        PanelTgsHriIni2.setLayout(PanelTgsHriIni2Layout);
        PanelTgsHriIni2Layout.setHorizontalGroup(
            PanelTgsHriIni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelTgsHriIni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTgsHriIni2Layout.createSequentialGroup()
                        .addComponent(ProgresTugas2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PresentaseProgres2)
                        .addGap(14, 14, 14))
                    .addGroup(PanelTgsHriIni2Layout.createSequentialGroup()
                        .addGroup(PanelTgsHriIni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuTanggalDeadline4)
                            .addComponent(WaktuTanggalDeadline5))
                        .addGap(0, 295, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JudulTugas3)
                .addGap(134, 134, 134))
        );
        PanelTgsHriIni2Layout.setVerticalGroup(
            PanelTgsHriIni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulTugas3)
                .addGap(2, 2, 2)
                .addComponent(WaktuTanggalDeadline4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaktuTanggalDeadline5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(PanelTgsHriIni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni2Layout.createSequentialGroup()
                        .addComponent(ProgresTugas2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni2Layout.createSequentialGroup()
                        .addComponent(PresentaseProgres2)
                        .addContainerGap())))
        );

        PanelTgsHriIni3.setBackground(new java.awt.Color(255, 255, 255));

        JudulTugas4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulTugas4.setForeground(new java.awt.Color(33, 52, 72));
        JudulTugas4.setText("Judul Tugas");

        ProgresTugas3.setBackground(new java.awt.Color(255, 222, 183));

        WaktuTanggalDeadline6.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline6.setText("Deadline");

        PresentaseProgres3.setForeground(new java.awt.Color(33, 52, 72));
        PresentaseProgres3.setText("0%");

        WaktuTanggalDeadline7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        WaktuTanggalDeadline7.setForeground(new java.awt.Color(33, 52, 72));
        WaktuTanggalDeadline7.setText("Deskripsi");

        javax.swing.GroupLayout PanelTgsHriIni3Layout = new javax.swing.GroupLayout(PanelTgsHriIni3);
        PanelTgsHriIni3.setLayout(PanelTgsHriIni3Layout);
        PanelTgsHriIni3Layout.setHorizontalGroup(
            PanelTgsHriIni3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelTgsHriIni3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTgsHriIni3Layout.createSequentialGroup()
                        .addComponent(ProgresTugas3, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PresentaseProgres3)
                        .addGap(14, 14, 14))
                    .addGroup(PanelTgsHriIni3Layout.createSequentialGroup()
                        .addGroup(PanelTgsHriIni3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuTanggalDeadline6)
                            .addComponent(WaktuTanggalDeadline7))
                        .addGap(0, 295, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JudulTugas4)
                .addGap(134, 134, 134))
        );
        PanelTgsHriIni3Layout.setVerticalGroup(
            PanelTgsHriIni3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTgsHriIni3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(JudulTugas4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaktuTanggalDeadline6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaktuTanggalDeadline7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(PanelTgsHriIni3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni3Layout.createSequentialGroup()
                        .addComponent(ProgresTugas3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTgsHriIni3Layout.createSequentialGroup()
                        .addComponent(PresentaseProgres3)
                        .addContainerGap())))
        );

        Navbar2.setBackground(new java.awt.Color(247, 247, 247));
        Navbar2.setForeground(new java.awt.Color(247, 247, 247));

        Home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Beranda.png"))); // NOI18N
        Home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home2MouseClicked(evt);
            }
        });

        Tugas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tugas.png"))); // NOI18N
        Tugas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tugas2MouseClicked(evt);
            }
        });

        Timer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Timmer.png"))); // NOI18N
        Timer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Timer2MouseClicked(evt);
            }
        });

        Statistik2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Statistik.png"))); // NOI18N
        Statistik2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Statistik2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Navbar2Layout = new javax.swing.GroupLayout(Navbar2);
        Navbar2.setLayout(Navbar2Layout);
        Navbar2Layout.setHorizontalGroup(
            Navbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navbar2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Home2)
                .addGap(40, 40, 40)
                .addComponent(Tugas2)
                .addGap(40, 40, 40)
                .addComponent(Timer2)
                .addGap(40, 40, 40)
                .addComponent(Statistik2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        Navbar2Layout.setVerticalGroup(
            Navbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navbar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Navbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tugas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Timer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Statistik2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NewBack.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        AddTugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NewAddTugas.png"))); // NOI18N
        AddTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTugasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(104, 104, 104)
                        .addComponent(JudulTugas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddTugas))
                    .addComponent(PanelTgsHriIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTgsHriIni1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTgsHriIni2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTgsHriIni3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulTugas1)
                    .addComponent(AddTugas)
                    .addComponent(Back))
                .addGap(29, 29, 29)
                .addComponent(PanelTgsHriIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelTgsHriIni3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelTgsHriIni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelTgsHriIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Navbar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Statistik2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Statistik2MouseClicked
        new Statistik().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Statistik2MouseClicked

    private void Timer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Timer2MouseClicked
        new Timer().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Timer2MouseClicked

    private void Tugas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tugas2MouseClicked
        new Tugas().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Tugas2MouseClicked

    private void Home2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home2MouseClicked
        new Dashboards().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Home2MouseClicked

    private void AddTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTugasMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_AddTugasMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new Dashboards().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddTugas;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JLabel Home2;
    private javax.swing.JLabel JudulTugas;
    private javax.swing.JLabel JudulTugas1;
    private javax.swing.JLabel JudulTugas2;
    private javax.swing.JLabel JudulTugas3;
    private javax.swing.JLabel JudulTugas4;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel Navbar1;
    private javax.swing.JPanel Navbar2;
    private java.awt.Panel PanelTgsHriIni;
    private java.awt.Panel PanelTgsHriIni1;
    private java.awt.Panel PanelTgsHriIni2;
    private java.awt.Panel PanelTgsHriIni3;
    private javax.swing.JLabel PresentaseProgres;
    private javax.swing.JLabel PresentaseProgres1;
    private javax.swing.JLabel PresentaseProgres2;
    private javax.swing.JLabel PresentaseProgres3;
    private javax.swing.JProgressBar ProgresTugas;
    private javax.swing.JProgressBar ProgresTugas1;
    private javax.swing.JProgressBar ProgresTugas2;
    private javax.swing.JProgressBar ProgresTugas3;
    private javax.swing.JLabel Statistik;
    private javax.swing.JLabel Statistik1;
    private javax.swing.JLabel Statistik2;
    private javax.swing.JLabel Timer;
    private javax.swing.JLabel Timer1;
    private javax.swing.JLabel Timer2;
    private javax.swing.JLabel Tugas;
    private javax.swing.JLabel Tugas1;
    private javax.swing.JLabel Tugas2;
    private javax.swing.JLabel WaktuTanggalDeadline;
    private javax.swing.JLabel WaktuTanggalDeadline1;
    private javax.swing.JLabel WaktuTanggalDeadline2;
    private javax.swing.JLabel WaktuTanggalDeadline3;
    private javax.swing.JLabel WaktuTanggalDeadline4;
    private javax.swing.JLabel WaktuTanggalDeadline5;
    private javax.swing.JLabel WaktuTanggalDeadline6;
    private javax.swing.JLabel WaktuTanggalDeadline7;
    // End of variables declaration//GEN-END:variables
}
